"""init

Revision ID: 0874267cb6ce
Revises: 
Create Date: 2026-06-01 09:11:31.333465

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0874267cb6ce'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('articulation_card',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('media', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('answer_type', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('automation_card',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('sound', sa.String(), nullable=False),
    sa.Column('road_type', sa.Integer(), nullable=False),
    sa.Column('frequency', sa.Integer(), nullable=False),
    sa.Column('speed', sa.Integer(), nullable=False),
    sa.Column('media', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('differentiation_card',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('media', sa.String(), nullable=False),
    sa.Column('sound', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('personal_task',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('media', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('answer_type', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('task_types',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('card',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('type_id', sa.Integer(), nullable=False),
    sa.Column('content_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['type_id'], ['task_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('card')
    op.drop_table('task_types')
    op.drop_table('personal_task')
    op.drop_table('differentiation_card')
    op.drop_table('automation_card')
    op.drop_table('articulation_card')
    # ### end Alembic commands ###
