"""all tables

Revision ID: 152edd9df056
Revises: 0874267cb6ce
Create Date: 2026-06-01 09:26:09.988902

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '152edd9df056'
down_revision: Union[str, Sequence[str], None] = '0874267cb6ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('logoped',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('surname', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('module',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pupil',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('surname', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('logoped_auth',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('logoped_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['logoped_id'], ['logoped.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('logoped_id')
    )
    op.create_table('logoped_module',
    sa.Column('logoped_id', sa.Integer(), nullable=False),
    sa.Column('module_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['logoped_id'], ['logoped.id'], ),
    sa.ForeignKeyConstraint(['module_id'], ['module.id'], ),
    sa.PrimaryKeyConstraint('logoped_id', 'module_id')
    )
    op.create_table('logoped_pupil',
    sa.Column('logoped_id', sa.Integer(), nullable=False),
    sa.Column('pupil_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['logoped_id'], ['logoped.id'], ),
    sa.ForeignKeyConstraint(['pupil_id'], ['pupil.id'], ),
    sa.PrimaryKeyConstraint('logoped_id', 'pupil_id')
    )
    op.create_table('pupil_homework',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pupil_id', sa.Integer(), nullable=False),
    sa.Column('module_id', sa.Integer(), nullable=False),
    sa.Column('public_token', sa.String(), nullable=False),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['module_id'], ['module.id'], ),
    sa.ForeignKeyConstraint(['pupil_id'], ['pupil.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('public_token')
    )
    op.create_table('task',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('type_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['type_id'], ['task_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('module_task',
    sa.Column('module_id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['module_id'], ['module.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['task.id'], ),
    sa.PrimaryKeyConstraint('module_id', 'task_id')
    )
    op.create_table('pupil_answer',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('homework_id', sa.Integer(), nullable=False),
    sa.Column('card_id', sa.Integer(), nullable=False),
    sa.Column('answer_url', sa.String(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['card_id'], ['card.id'], ),
    sa.ForeignKeyConstraint(['homework_id'], ['pupil_homework.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('task_card',
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('card_id', sa.Integer(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['card_id'], ['card.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['task.id'], ),
    sa.PrimaryKeyConstraint('task_id', 'card_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('task_card')
    op.drop_table('pupil_answer')
    op.drop_table('module_task')
    op.drop_table('task')
    op.drop_table('pupil_homework')
    op.drop_table('logoped_pupil')
    op.drop_table('logoped_module')
    op.drop_table('logoped_auth')
    op.drop_table('pupil')
    op.drop_table('module')
    op.drop_table('logoped')
    # ### end Alembic commands ###
