from app.models.base import Base
from app.models.task_type import TaskType
from app.models.card import Card
from app.models.articulation_card import ArticulationCard
from app.models.differentiation_card import DifferentiationCard
from app.models.automation_card import AutomationCard
from app.models.personal_task import PersonalTaskCard
from app.models.task import Task
from app.models.task_card import TaskCard
from app.models.module import Module
from app.models.module_task import ModuleTask
from app.models.logoped import Logoped
from app.models.logoped_auth import LogopedAuth
from app.models.pupil import Pupil
from app.models.logoped_pupil import LogopedPupil
from app.models.logoped_module import LogopedModule
from app.models.pupil_homework import PupilHomework
from app.models.pupil_answer import PupilAnswer